### ISSUE TITLE
cant render anything

### ISSUE THREAD

**Issue by TomerGamerTV** [ThatRedox/ChunkyClPlugin#11]
then I'm trying to start rendering everything as just blue or green and not showing anything
to fix it I have to disable the plugin and reload the saved file

using the latest version
GPU: 1060 6G

**Comment by TomerGamerTV** [comment]
![image](https://user-images.githubusercontent.com/44266242/118358240-9a114400-b586-11eb-9e0a-8eaf68081550.png)
this is what i see then i want to render with gpu

**Comment by YveIce** [comment]
> this is what i see then i want to render with gpu

As i found out, this happens if your camera is set to parallel projection (Like when loading Presets for Isometric view). just set it to "Standard" and it should work.

**Comment by ThatRedox** [comment]
The renderer has been completely rewritten and I cannot reproduce this issue. Closing for now unless you encounter this issue again.
