### ISSUE TITLE
Bigger sky cache resolution crashes on scene load

### ISSUE THREAD

**Issue by ShirleyNekoDev** [ThatRedox/ChunkyClPlugin#16]
The `GpuRayTracer` initializes its `skyImage` cache on creation using the default `skyTextureResolution` of 128.
Once the tracer initializes the scene and calls `generateSky` it loads the scene's sky resolution (which in my case was 256).
When it then tries to write into the smaller `skyImage` cache we get an index out of bounds exception (https://github.com/alexhliu/ChunkyClPlugin/blob/master/src/main/java/chunkycl/GpuRayTracer.java#L549).
The solution would probably be to check if the size changed in line 526 and then create a new a array for the cache (which then could not be final).

**Comment by ThatRedox** [comment]
Fixed. The sky texture size is now set based on the scene sky texture resolution. High resolution sky textures work in the latest development builds.
