### ISSUE TITLE
Latest Stable Build Expired

### ISSUE THREAD

**Issue by mitgobla** [ThatRedox/ChunkyClPlugin#17]
The latest stable build download link returns a 404 error as the artifact has expired (>90 days).

The link: [https://nightly.link/alexhliu/ChunkyClPlugin/workflows/stable/stable/ChunkyClPlugin.zip](https://nightly.link/alexhliu/ChunkyClPlugin/workflows/stable/stable/ChunkyClPlugin.zip)

Is there an updated link or download of the stable release artifact? 

The latest artifact on the stable action does not load in Chunker, the option to select the CL rendered does not exist.
The latest development build does not work on Chunker 2.4.0-187-ga3af940a, it renders a white screen.

**Comment by ThatRedox** [comment]
There is a new build in development and I've updated and reenabled builds for stable. It should run within 24 hours. The old stable build did not work in latest Chunky. The latest development build should be working. Are you sure your camera is not inside a block?
