### ISSUE TITLE
block models not working

### ISSUE THREAD

**Issue by guid118** [ThatRedox/ChunkyClPlugin#23]
when selecting the ChunkyCIRenderer, all blocks that are not full blocks(fences, flowers, lanterns, torches, chests, etc) try to become full blocks anyway, weird blocks

![image](https://user-images.githubusercontent.com/64263726/146658946-02d0b6b0-efc8-4c0d-ae3c-a655869cb7ac.png)
(spruce blocks are supposed to be fences, lanterns don't look normal and the flowers in the back are also full blocks)

**Comment by ThatRedox** [comment]
Only full blocks were supported previously. The newest development builds properly support non-full blocks such as fences etc.
