### ISSUE TITLE
Not rendering below y=0

### ISSUE THREAD

**Issue by belkovTV** [ThatRedox/ChunkyClPlugin#28]
I've been having trouble with rendering properly with stuff below y=0, like in the example below a ship and lake being below y=0:

![image](https://user-images.githubusercontent.com/48180910/156230926-4fc3dec2-a624-4751-9a13-c69d7f29cf69.png)

**Comment by ThatRedox** [comment]
Rendering below `y=0` works. Probably need to set y clip correctly in Chunky.
