### ISSUE TITLE
ChunkyClPlugin.jar failed to load => CL_BUILD_PROGRAM_FAILURE

### ISSUE THREAD

**Issue by Lonaasan** [ThatRedox/ChunkyClPlugin#35]
The Plugin on stable does not support RTX 3060

> Plugin ChunkyClPlugin.jar failed to load.
> org.jocl.CLException: CL_BUILD_PROGRAM_FAILURE
> Build log for device 0:
> <kernel>:328:61: error: passing '__generic float *' to parameter of type 'float *' changes address space of pointer
>             float t1 = aabbIntersectDist(origin, direction, (float*)(node+1));
>                                                             ^~~~~~~~~~~~~~~~
> <kernel>:26:66: note: passing argument to parameter 'bounds' here
> float aabbIntersectDist(float3 *origin, float3 *direction, float bounds[6]);
>                                                                  ^
> <kernel>:330:61: error: passing '__generic float *' to parameter of type 'float *' changes address space of pointer
>             float t2 = aabbIntersectDist(origin, direction, (float*)(node+1));
>                                                             ^~~~~~~~~~~~~~~~
> <kernel>:26:66: note: passing argument to parameter 'bounds' here
> float aabbIntersectDist(float3 *origin, float3 *direction, float bounds[6]);
>                                                                  ^
> 
> 
> 	at org.jocl.CL.clCompileProgram(CL.java:11994)
> 	at chunkycl.KernelLoader.loadProgram(KernelLoader.java:38)
> 	at chunkycl.GpuRayTracer.<init>(GpuRayTracer.java:155)
> 	at chunkycl.GpuRayTracer.getTracer(GpuRayTracer.java:179)
> 	at chunkycl.AbstractOpenClRenderer.<init>(AbstractOpenClRenderer.java:20)
> 	at chunkycl.OpenClRenderer.<init>(OpenClRenderer.java:17)
> 	at chunkycl.ChunkyCl.attach(ChunkyCl.java:26)
> 	at se.llbit.chunky.main.Chunky.lambda$loadPlugins$5(Chunky.java:269)
> 	at se.llbit.chunky.plugin.ChunkyPlugin.load(ChunkyPlugin.java:90)
> 	at se.llbit.chunky.main.Chunky.loadPlugins(Chunky.java:259)
> 	at se.llbit.chunky.main.Chunky.main(Chunky.java:213)
>

**Comment by ThatRedox** [comment]
Fixed in 65e9466800c67404c2f624b61ff77b5b16d4a52d.
